CREATE TABLE NPCLoot
(
    NPCLootID SERIAL CONSTRAINT PK_NPCLoot PRIMARY KEY,
    NPCID INTEGER NOT NULL CONSTRAINT FK_NPCLoot_NPC REFERENCES NPC,
    ItemID INTEGER NOT NULL CONSTRAINT FK_NPCLoot_Item REFERENCES Item,
    DropRate REAL NOT NULL
);