CREATE TABLE NPCSpawn
(
    NPCSpawnID SERIAL CONSTRAINT PK_NPCSpawn PRIMARY KEY,
    NPCID INTEGER NOT NULL CONSTRAINT FK_NPCSpawn_NPC REFERENCES NPC,
    Position POINT NOT NULL,
    Rotation REAL NOT NULL,
    MapNumber INTEGER NOT NULL,
    Frequency INTERVAL NOT NULL,
    Flags INTEGER NOT NULL
);